name: Rust

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cd music-cache && cargo build --verbose
    - name: Run tests
      run: cd music-cache && cargo test --verbose --features integration-tests
